# Generated by Django 6.0.2 on 2026-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0002_alter_employe_departement_boutique_employe_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employe',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employe',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='num_cnps',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro CNPS'),
        ),
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AddField(
            model_name='employe',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
