# Generated by Django 6.0.2 on 2026-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0003_employe_commune_employe_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('employe', 'Employé'), ('rh', 'Ressources Humaines (RH)'), ('admin', 'Administrateur')], default='employe', help_text="Détermine les droits d'accès de la personne dans le système.", max_length=10, verbose_name='Rôle'),
        ),
    ]
