# Generated by Django 6.0.2 on 2026-02-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0005_fix_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('paye', 'Congé payé'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('exceptionnel', 'Congé exceptionnel'), ('sans_solde', 'Congé sans solde')], max_length=20),
        ),
    ]
