# Generated by Django 6.0.2 on 2026-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0007_data_conge_annuel_to_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('employe', 'Employé'), ('rh', 'Ressources Humaines (RH)'), ('daf', 'DAF'), ('admin', 'Administrateur')], default='employe', help_text="Détermine les droits d'accès de la personne dans le système.", max_length=10, verbose_name='Rôle'),
        ),
    ]
