# Generated by Django 5.0 on 2026-03-02 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0009_permission_jours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('employe_ajoute', 'Employé ajouté'), ('employe_modifie', 'Employé modifié'), ('employe_supprime', 'Employé supprimé'), ('conge_demande', 'Congé demandé'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('permission_demande', 'Permission demandée'), ('permission_approuve', 'Permission approuvée'), ('permission_refuse', 'Permission refusée'), ('presence_marquee', 'Présence marquée'), ('boutique_ajoutee', 'Boutique ajoutée'), ('boutique_modifiee', 'Boutique modifiée'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_log', to='SYGEPE.employe', verbose_name='Employé concerné')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_log', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Action RH',
                'verbose_name_plural': 'Historique des actions RH',
                'ordering': ['-date'],
            },
        ),
    ]
