# Generated by Django 5.0 on 2026-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0010_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('paye', 'Congé annuel'), ('maternite', 'Congé maternité')], max_length=20),
        ),
    ]
