# Generated by Django 5.0 on 2026-03-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0011_reduce_type_conge_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='piece_justificative',
            field=models.FileField(blank=True, null=True, upload_to='conges/justificatifs/', verbose_name='Pièce justificative'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('paye', 'Congé annuel'), ('maternite', 'Congé maternité'), ('maladie', 'Congé maladie')], max_length=20),
        ),
    ]
