# Generated by Django 5.0 on 2026-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0012_add_conge_maladie_piece_justificative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('employe', 'Employé'), ('rh', 'Ressources Humaines (RH)'), ('daf', 'DAF'), ('admin', 'Administrateur'), ('dir_commercial', 'Directeur Commercial'), ('resp_logistique', 'Responsable Logistique'), ('resp_reabo', 'Responsable Réabo'), ('chef_comptable', 'Chef Comptable')], default='employe', help_text="Détermine les droits d'accès de la personne dans le système.", max_length=16, verbose_name='Rôle'),
        ),
    ]
