# Generated by Django 6.0.2 on 2026-03-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0013_remove_boutique'),
        ('SYGEPE', '0014_permission_two_step_validation'),
    ]

    operations = [
    ]
