# Generated by Django 5.0 on 2026-03-14 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0015_merge_20260314_1801'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('employe_ajoute', 'Employé ajouté'), ('employe_modifie', 'Employé modifié'), ('employe_supprime', 'Employé supprimé'), ('conge_demande', 'Congé demandé'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('permission_demande', 'Permission demandée'), ('permission_approuve', 'Permission approuvée'), ('permission_refuse', 'Permission refusée'), ('presence_marquee', 'Présence marquée'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['date_debut', 'employe', 'statut'], name='conge_date_employe_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date', 'employe'], name='presence_date_employe_idx'),
        ),
    ]
