# Generated by Django 5.0 on 2026-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0016_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='num_cni',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numéro CNI'),
        ),
    ]
