# Generated by Django 5.0 on 2026-03-30 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0017_employe_num_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='conge_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fractions', to='SYGEPE.conge', verbose_name="Congé d'origine (fractionnement)"),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('employe_ajoute', 'Employé ajouté'), ('employe_modifie', 'Employé modifié'), ('employe_supprime', 'Employé supprimé'), ('conge_demande', 'Congé demandé'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('conge_modifie', 'Congé modifié / fractionné'), ('permission_demande', 'Permission demandée'), ('permission_approuve', 'Permission approuvée'), ('permission_refuse', 'Permission refusée'), ('presence_marquee', 'Présence marquée'), ('autre', 'Autre')], max_length=30),
        ),
    ]
