# Generated by Django 5.0 on 2026-03-30 10:35

import SYGEPE.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0018_conge_conge_parent_alter_actionlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('employe_ajoute', 'Employé ajouté'), ('employe_modifie', 'Employé modifié'), ('employe_supprime', 'Employé supprimé'), ('conge_demande', 'Congé demandé'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('conge_modifie', 'Congé modifié / fractionné'), ('absence_demandee', 'Absence demandée'), ('absence_approuvee', 'Absence approuvée'), ('absence_refusee', 'Absence refusée'), ('permission_demande', 'Permission demandée'), ('permission_approuve', 'Permission approuvée'), ('permission_refuse', 'Permission refusée'), ('presence_marquee', 'Présence marquée'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('mission_pro', 'Mission professionnelle'), ('formation_interne', 'Formation interne'), ('atelier', 'Atelier')], max_length=30, verbose_name="Type d'absence")),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_valideur', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='SYGEPE.employe')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_demande'],
            },
            bases=(SYGEPE.models.PeriodeMixin, models.Model),
        ),
    ]
