# Generated by Django 5.0 on 2026-03-30 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPE', '0019_alter_actionlog_action_absence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='date_validation_responsable',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='valideur_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees_resp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide_responsable', 'Validé par responsable'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('employe_ajoute', 'Employé ajouté'), ('employe_modifie', 'Employé modifié'), ('employe_supprime', 'Employé supprimé'), ('conge_demande', 'Congé demandé'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('conge_modifie', 'Congé modifié / fractionné'), ('absence_demandee', 'Absence demandée'), ('absence_validee_resp', 'Absence validée par responsable'), ('absence_approuvee', 'Absence approuvée'), ('absence_refusee', 'Absence refusée'), ('permission_demande', 'Permission demandée'), ('permission_approuve', 'Permission approuvée'), ('permission_refuse', 'Permission refusée'), ('presence_marquee', 'Présence marquée'), ('autre', 'Autre')], max_length=30),
        ),
    ]
